#!/usr/bin/env bash
#----------------------------------------------------------
# Shebe CI MCP Registry Publish Script
#
# Publishes Shebe to the official MCP Registry using mcp-publisher.
# Requires DNS verification to have been completed (see Phase 1 of work plan 019).
#
# Usage:
#   ./scripts/ci-mcpb-publish.sh              # Run in GitLab CI
#   ./scripts/ci-mcpb-publish.sh --preview    # Local preview (validate only)
#   ./scripts/ci-mcpb-publish.sh --verify     # Check if server is published
#
# Required environment variables (GitLab CI secrets):
#   MCP_PRIVATE_KEY     - Ed25519 private key (PEM format) for DNS verification
#
# Required files:
#   releases/server.json - Server metadata (generated by ci-mcpb.sh)
#
# Optional environment variables:
#   MCP_DOMAIN          - Domain for DNS verification (default: oss.rhobimd.health)
#   RELEASE_DIR         - Directory containing server.json (default: releases)
#----------------------------------------------------------
set -euo pipefail

# Use CI_PROJECT_DIR in GitLab CI, otherwise calculate from script location
if [[ -n "${CI_PROJECT_DIR:-}" ]]; then
    REPO_ROOT="${CI_PROJECT_DIR}"
else
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
fi

# Configuration
RELEASE_DIR="${RELEASE_DIR:-releases}"
MCP_DOMAIN="${MCP_DOMAIN:-oss.rhobimd.health}"
MCP_REGISTRY_API="https://registry.modelcontextprotocol.io/v0"
MCP_KEY_FILE="/tmp/mcp-key-$$.pem"
PREVIEW_MODE=false
VERIFY_MODE=false

#----------------------------------------------------------
# Functions
#----------------------------------------------------------

log() {
    echo "[ci-mcpb-publish] $*"
}

error() {
    echo "[ci-mcpb-publish] ERROR: $*" >&2
    exit 1
}

cleanup() {
    # Remove temporary key file
    if [[ -f "${MCP_KEY_FILE}" ]]; then
        rm -f "${MCP_KEY_FILE}"
        log "Cleaned up temporary key file"
    fi
}

# Ensure cleanup on exit
trap cleanup EXIT

# Check required dependencies
check_dependencies() {
    local missing=()
    for cmd in curl jq; do
        if ! command -v "${cmd}" &> /dev/null; then
            missing+=("${cmd}")
        fi
    done
    if [[ ${#missing[@]} -gt 0 ]]; then
        error "Missing required commands: ${missing[*]}"
    fi
}

# Verify mcp-publisher is available
check_mcp_publisher() {
    if ! command -v mcp-publisher &> /dev/null; then
        error "mcp-publisher not found - use rust-ci image with mcp-publisher pre-installed"
    fi
    log "mcp-publisher found: $(mcp-publisher --version 2>/dev/null || echo 'version unknown')"
}

# Write private key to temporary file with secure permissions
setup_private_key() {
    if [[ -z "${MCP_PRIVATE_KEY:-}" ]]; then
        error "MCP_PRIVATE_KEY environment variable not set"
    fi

    log "Setting up private key..."

    # Write key to temp file with restricted permissions
    # Handle both literal newlines and escaped \n in the key
    echo "${MCP_PRIVATE_KEY}" | sed 's/\\n/\n/g' > "${MCP_KEY_FILE}"
    chmod 600 "${MCP_KEY_FILE}"

    # Verify key format
    if ! grep -q "BEGIN.*PRIVATE KEY" "${MCP_KEY_FILE}"; then
        error "Invalid private key format - expected PEM format"
    fi

    log "Private key ready"
}

# Authenticate with MCP Registry using DNS verification
authenticate() {
    log "Authenticating with MCP Registry..."
    log "Domain: ${MCP_DOMAIN}"

    mcp-publisher login dns \
        --domain "${MCP_DOMAIN}" \
        --private-key-file "${MCP_KEY_FILE}"

    log "Authentication successful"
}

# Validate server.json before publishing
validate_server_json() {
    local server_json="${REPO_ROOT}/${RELEASE_DIR}/server.json"

    if [[ ! -f "${server_json}" ]]; then
        error "server.json not found: ${server_json}"
    fi

    log "Validating server.json..."

    # Basic JSON validation
    if ! jq empty "${server_json}" 2>/dev/null; then
        error "server.json is not valid JSON"
    fi

    # Check required fields
    local name version
    name=$(jq -r '.name // empty' "${server_json}")
    version=$(jq -r '.version // empty' "${server_json}")

    if [[ -z "${name}" ]]; then
        error "server.json missing required field: name"
    fi
    if [[ -z "${version}" ]]; then
        error "server.json missing required field: version"
    fi

    log "Server: ${name} v${version}"

    # Validate with mcp-publisher if authenticated
    if command -v mcp-publisher &> /dev/null; then
        if mcp-publisher validate "${server_json}" 2>/dev/null; then
            log "server.json validated by mcp-publisher"
        else
            log "Warning: mcp-publisher validation failed (may need authentication)"
        fi
    fi

    log "Validation complete"
}

# Publish server to MCP Registry
publish_to_registry() {
    local server_json="${REPO_ROOT}/${RELEASE_DIR}/server.json"

    log "Publishing to MCP Registry..."

    mcp-publisher publish "${server_json}"

    log "Publication successful!"
}

# Verify server appears in registry
verify_publication() {
    local server_json="${REPO_ROOT}/${RELEASE_DIR}/server.json"
    local name version

    if [[ -f "${server_json}" ]]; then
        name=$(jq -r '.name // empty' "${server_json}")
        version=$(jq -r '.version // empty' "${server_json}")
    else
        # Use default values for verify-only mode
        name="health.rhobimd.oss/shebe"
        version=""
    fi

    log "Verifying publication..."
    log "Searching for: shebe"

    local response
    response=$(curl -s "${MCP_REGISTRY_API}/servers?search=shebe" || echo '{"items":[]}')

    # Check if our server is in the results
    local found
    found=$(echo "${response}" | jq -r --arg name "${name}" '.items[]? | select(.name == $name) | .name' 2>/dev/null || echo "")

    if [[ -n "${found}" ]]; then
        log "Server found in registry: ${found}"
        if [[ -n "${version}" ]]; then
            local reg_version
            reg_version=$(echo "${response}" | jq -r --arg name "${name}" '.items[]? | select(.name == $name) | .version' 2>/dev/null || echo "")
            log "Registry version: ${reg_version}"
            if [[ "${reg_version}" == "${version}" ]]; then
                log "Version matches: ${version}"
            else
                log "Note: Registry version (${reg_version}) differs from local (${version})"
            fi
        fi
        return 0
    else
        log "Server not found in registry search results"
        log "Note: Registry may take a few minutes to update"
        return 1
    fi
}

# Display current authentication status
check_auth_status() {
    log "Checking authentication status..."

    if command -v mcp-publisher &> /dev/null; then
        mcp-publisher whoami 2>/dev/null || log "Not authenticated"
    else
        log "mcp-publisher not installed"
    fi
}

#----------------------------------------------------------
# Main
#----------------------------------------------------------

main() {
    # Parse arguments
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --preview)
                PREVIEW_MODE=true
                shift
                ;;
            --verify)
                VERIFY_MODE=true
                shift
                ;;
            --help|-h)
                echo "Usage: $0 [--preview] [--verify]"
                echo ""
                echo "Options:"
                echo "  --preview    Validate only, do not publish"
                echo "  --verify     Check if server is published in registry"
                echo ""
                echo "Environment variables:"
                echo "  MCP_PRIVATE_KEY    Ed25519 private key (PEM format)"
                echo "  MCP_DOMAIN         Domain for DNS auth (default: oss.rhobimd.health)"
                echo "  RELEASE_DIR        Directory with server.json (default: releases)"
                exit 0
                ;;
            *)
                error "Unknown argument: $1"
                ;;
        esac
    done

    cd "${REPO_ROOT}"

    # Check dependencies
    check_dependencies

    # Verify-only mode
    if [[ "${VERIFY_MODE}" == "true" ]]; then
        log "Verify mode - checking registry..."
        verify_publication
        exit 0
    fi

    # Validate server.json exists and is valid
    validate_server_json

    # Preview mode - just validate
    if [[ "${PREVIEW_MODE}" == "true" ]]; then
        log "Preview mode - skipping authentication and publication"
        log "server.json is valid and ready for publication"
        exit 0
    fi

    # Verify mcp-publisher is available
    check_mcp_publisher

    # Setup private key
    setup_private_key

    # Authenticate with registry
    authenticate

    # Check authentication status
    check_auth_status

    # Publish to registry
    publish_to_registry

    # Verify publication
    log "Waiting 5 seconds for registry to update..."
    sleep 5
    verify_publication || true

    log "Publication complete!"
    log "View at: https://registry.modelcontextprotocol.io/servers/health.rhobimd.oss/shebe"
}

main "$@"
